# Generated by Django 2.0.13 on 2019-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('cmd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LastBLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('srcIP', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pts', models.CharField(max_length=100)),
                ('srcIP', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
